import { renderHook } from '@testing-library/react-hooks';
import useCalendar from './useCalendar';
import { Year } from './types';

const thatDay = 'Sun Mar 20 2022 19:45:00 GMT+0100';
jest.useFakeTimers().setSystemTime(new Date(thatDay));

describe('useCalendar', function () {
  test('day', function () {
    const date = new Date(thatDay);
    const { result } = renderHook(() =>
      useCalendar({ date, view: 'day', weekStartsOn: 0 }),
    );
    const [day] = result.current;

    expect(day).toEqual({
      dayIndex: 0,
      dayOfMonth: 20,
      dayOfWeek: 'Sunday',
      dayOfYear: 79,
      isSameMonth: true,
      isToday: true,
      isWeekend: true,
    });
  });

  test('week starting on Sunday', function () {
    const date = new Date(thatDay);
    const { result } = renderHook(() => useCalendar({ date, view: 'week' }));
    const [week] = result.current;

    expect(week).toEqual({
      weekOfYear: 13,
      isCurrent: true,
      days: [
        {
          dayIndex: 0,
          dayOfMonth: 20,
          dayOfWeek: 'Sunday',
          dayOfYear: 79,
          isSameMonth: true,
          isToday: true,
          isWeekend: true,
        },
        {
          dayIndex: 1,
          dayOfMonth: 21,
          dayOfWeek: 'Monday',
          dayOfYear: 80,
          isSameMonth: true,
          isToday: false,
          isWeekend: false,
        },
        {
          dayIndex: 2,
          dayOfMonth: 22,
          dayOfWeek: 'Tuesday',
          dayOfYear: 81,
          isSameMonth: true,
          isToday: false,
          isWeekend: false,
        },
        {
          dayIndex: 3,
          dayOfMonth: 23,
          dayOfWeek: 'Wednesday',
          dayOfYear: 82,
          isSameMonth: true,
          isToday: false,
          isWeekend: false,
        },
        {
          dayIndex: 4,
          dayOfMonth: 24,
          dayOfWeek: 'Thursday',
          dayOfYear: 83,
          isSameMonth: true,
          isToday: false,
          isWeekend: false,
        },
        {
          dayIndex: 5,
          dayOfMonth: 25,
          dayOfWeek: 'Friday',
          dayOfYear: 84,
          isSameMonth: true,
          isToday: false,
          isWeekend: false,
        },
        {
          dayIndex: 6,
          dayOfMonth: 26,
          dayOfWeek: 'Saturday',
          dayOfYear: 85,
          isSameMonth: true,
          isToday: false,
          isWeekend: true,
        },
      ],
    });
  });

  test('week starting on Monday', function () {
    const date = new Date(thatDay);
    const { result } = renderHook(() =>
      useCalendar({ date, view: 'week', weekStartsOn: 1 }),
    );
    const [week] = result.current;

    expect(week).toEqual({
      weekOfYear: 13,
      isCurrent: true,
      days: [
        {
          dayIndex: 1,
          dayOfMonth: 14,
          dayOfWeek: 'Monday',
          dayOfYear: 73,
          isSameMonth: true,
          isToday: false,
          isWeekend: false,
        },
        {
          dayIndex: 2,
          dayOfMonth: 15,
          dayOfWeek: 'Tuesday',
          dayOfYear: 74,
          isSameMonth: true,
          isToday: false,
          isWeekend: false,
        },
        {
          dayIndex: 3,
          dayOfMonth: 16,
          dayOfWeek: 'Wednesday',
          dayOfYear: 75,
          isSameMonth: true,
          isToday: false,
          isWeekend: false,
        },
        {
          dayIndex: 4,
          dayOfMonth: 17,
          dayOfWeek: 'Thursday',
          dayOfYear: 76,
          isSameMonth: true,
          isToday: false,
          isWeekend: false,
        },
        {
          dayIndex: 5,
          dayOfMonth: 18,
          dayOfWeek: 'Friday',
          dayOfYear: 77,
          isSameMonth: true,
          isToday: false,
          isWeekend: false,
        },
        {
          dayIndex: 6,
          dayOfMonth: 19,
          dayOfWeek: 'Saturday',
          dayOfYear: 78,
          isSameMonth: true,
          isToday: false,
          isWeekend: true,
        },
        {
          dayIndex: 0,
          dayOfMonth: 20,
          dayOfWeek: 'Sunday',
          dayOfYear: 79,
          isSameMonth: true,
          isToday: true,
          isWeekend: true,
        },
      ],
    });
  });

  test('month starting on Sunday', function () {
    const date = new Date(thatDay);
    const { result } = renderHook(() => useCalendar({ date, view: 'month' }));
    const [month] = result.current;

    expect(month).toEqual({
      monthIndex: 2,
      monthOfYear: 'March',
      isCurrent: true,
      weeks: [
        {
          weekOfYear: 10,
          isCurrent: false,
          days: [
            {
              dayIndex: 0,
              dayOfMonth: 27,
              dayOfWeek: 'Sunday',
              dayOfYear: 58,
              isSameMonth: false,
              isToday: false,
              isWeekend: true,
            },
            {
              dayIndex: 1,
              dayOfMonth: 28,
              dayOfWeek: 'Monday',
              dayOfYear: 59,
              isSameMonth: false,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 2,
              dayOfMonth: 1,
              dayOfWeek: 'Tuesday',
              dayOfYear: 60,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 3,
              dayOfMonth: 2,
              dayOfWeek: 'Wednesday',
              dayOfYear: 61,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 4,
              dayOfMonth: 3,
              dayOfWeek: 'Thursday',
              dayOfYear: 62,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 5,
              dayOfMonth: 4,
              dayOfWeek: 'Friday',
              dayOfYear: 63,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 6,
              dayOfMonth: 5,
              dayOfWeek: 'Saturday',
              dayOfYear: 64,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
          ],
        },
        {
          weekOfYear: 11,
          isCurrent: false,
          days: [
            {
              dayIndex: 0,
              dayOfMonth: 6,
              dayOfWeek: 'Sunday',
              dayOfYear: 65,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
            {
              dayIndex: 1,
              dayOfMonth: 7,
              dayOfWeek: 'Monday',
              dayOfYear: 66,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 2,
              dayOfMonth: 8,
              dayOfWeek: 'Tuesday',
              dayOfYear: 67,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 3,
              dayOfMonth: 9,
              dayOfWeek: 'Wednesday',
              dayOfYear: 68,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 4,
              dayOfMonth: 10,
              dayOfWeek: 'Thursday',
              dayOfYear: 69,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 5,
              dayOfMonth: 11,
              dayOfWeek: 'Friday',
              dayOfYear: 70,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 6,
              dayOfMonth: 12,
              dayOfWeek: 'Saturday',
              dayOfYear: 71,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
          ],
        },
        {
          weekOfYear: 12,
          isCurrent: false,
          days: [
            {
              dayIndex: 0,
              dayOfMonth: 13,
              dayOfWeek: 'Sunday',
              dayOfYear: 72,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
            {
              dayIndex: 1,
              dayOfMonth: 14,
              dayOfWeek: 'Monday',
              dayOfYear: 73,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 2,
              dayOfMonth: 15,
              dayOfWeek: 'Tuesday',
              dayOfYear: 74,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 3,
              dayOfMonth: 16,
              dayOfWeek: 'Wednesday',
              dayOfYear: 75,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 4,
              dayOfMonth: 17,
              dayOfWeek: 'Thursday',
              dayOfYear: 76,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 5,
              dayOfMonth: 18,
              dayOfWeek: 'Friday',
              dayOfYear: 77,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 6,
              dayOfMonth: 19,
              dayOfWeek: 'Saturday',
              dayOfYear: 78,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
          ],
        },
        {
          weekOfYear: 13,
          isCurrent: true,
          days: [
            {
              dayIndex: 0,
              dayOfMonth: 20,
              dayOfWeek: 'Sunday',
              dayOfYear: 79,
              isSameMonth: true,
              isToday: true,
              isWeekend: true,
            },
            {
              dayIndex: 1,
              dayOfMonth: 21,
              dayOfWeek: 'Monday',
              dayOfYear: 80,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 2,
              dayOfMonth: 22,
              dayOfWeek: 'Tuesday',
              dayOfYear: 81,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 3,
              dayOfMonth: 23,
              dayOfWeek: 'Wednesday',
              dayOfYear: 82,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 4,
              dayOfMonth: 24,
              dayOfWeek: 'Thursday',
              dayOfYear: 83,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 5,
              dayOfMonth: 25,
              dayOfWeek: 'Friday',
              dayOfYear: 84,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 6,
              dayOfMonth: 26,
              dayOfWeek: 'Saturday',
              dayOfYear: 85,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
          ],
        },
        {
          weekOfYear: 14,
          isCurrent: false,
          days: [
            {
              dayIndex: 0,
              dayOfMonth: 27,
              dayOfWeek: 'Sunday',
              dayOfYear: 86,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
            {
              dayIndex: 1,
              dayOfMonth: 28,
              dayOfWeek: 'Monday',
              dayOfYear: 87,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 2,
              dayOfMonth: 29,
              dayOfWeek: 'Tuesday',
              dayOfYear: 88,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 3,
              dayOfMonth: 30,
              dayOfWeek: 'Wednesday',
              dayOfYear: 89,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 4,
              dayOfMonth: 31,
              dayOfWeek: 'Thursday',
              dayOfYear: 90,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 5,
              dayOfMonth: 1,
              dayOfWeek: 'Friday',
              dayOfYear: 91,
              isSameMonth: false,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 6,
              dayOfMonth: 2,
              dayOfWeek: 'Saturday',
              dayOfYear: 92,
              isSameMonth: false,
              isToday: false,
              isWeekend: true,
            },
          ],
        },
      ],
    });
  });

  test('month starting on Monday', function () {
    const date = new Date(thatDay);
    const { result } = renderHook(() =>
      useCalendar({ date, view: 'month', weekStartsOn: 1 }),
    );
    const [month] = result.current;

    expect(month).toEqual({
      monthIndex: 2,
      monthOfYear: 'March',
      isCurrent: true,
      weeks: [
        {
          weekOfYear: 10,
          isCurrent: false,
          days: [
            {
              dayIndex: 1,
              dayOfMonth: 28,
              dayOfWeek: 'Monday',
              dayOfYear: 59,
              isSameMonth: false,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 2,
              dayOfMonth: 1,
              dayOfWeek: 'Tuesday',
              dayOfYear: 60,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 3,
              dayOfMonth: 2,
              dayOfWeek: 'Wednesday',
              dayOfYear: 61,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 4,
              dayOfMonth: 3,
              dayOfWeek: 'Thursday',
              dayOfYear: 62,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 5,
              dayOfMonth: 4,
              dayOfWeek: 'Friday',
              dayOfYear: 63,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 6,
              dayOfMonth: 5,
              dayOfWeek: 'Saturday',
              dayOfYear: 64,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
            {
              dayIndex: 0,
              dayOfMonth: 6,
              dayOfWeek: 'Sunday',
              dayOfYear: 65,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
          ],
        },
        {
          weekOfYear: 11,
          isCurrent: false,
          days: [
            {
              dayIndex: 1,
              dayOfMonth: 7,
              dayOfWeek: 'Monday',
              dayOfYear: 66,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 2,
              dayOfMonth: 8,
              dayOfWeek: 'Tuesday',
              dayOfYear: 67,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 3,
              dayOfMonth: 9,
              dayOfWeek: 'Wednesday',
              dayOfYear: 68,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 4,
              dayOfMonth: 10,
              dayOfWeek: 'Thursday',
              dayOfYear: 69,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 5,
              dayOfMonth: 11,
              dayOfWeek: 'Friday',
              dayOfYear: 70,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 6,
              dayOfMonth: 12,
              dayOfWeek: 'Saturday',
              dayOfYear: 71,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
            {
              dayIndex: 0,
              dayOfMonth: 13,
              dayOfWeek: 'Sunday',
              dayOfYear: 72,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
          ],
        },
        {
          weekOfYear: 12,
          isCurrent: false,
          days: [
            {
              dayIndex: 1,
              dayOfMonth: 14,
              dayOfWeek: 'Monday',
              dayOfYear: 73,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 2,
              dayOfMonth: 15,
              dayOfWeek: 'Tuesday',
              dayOfYear: 74,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 3,
              dayOfMonth: 16,
              dayOfWeek: 'Wednesday',
              dayOfYear: 75,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 4,
              dayOfMonth: 17,
              dayOfWeek: 'Thursday',
              dayOfYear: 76,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 5,
              dayOfMonth: 18,
              dayOfWeek: 'Friday',
              dayOfYear: 77,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 6,
              dayOfMonth: 19,
              dayOfWeek: 'Saturday',
              dayOfYear: 78,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
            {
              dayIndex: 0,
              dayOfMonth: 20,
              dayOfWeek: 'Sunday',
              dayOfYear: 79,
              isSameMonth: true,
              isToday: true,
              isWeekend: true,
            },
          ],
        },
        {
          weekOfYear: 13,
          isCurrent: true,
          days: [
            {
              dayIndex: 1,
              dayOfMonth: 21,
              dayOfWeek: 'Monday',
              dayOfYear: 80,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 2,
              dayOfMonth: 22,
              dayOfWeek: 'Tuesday',
              dayOfYear: 81,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 3,
              dayOfMonth: 23,
              dayOfWeek: 'Wednesday',
              dayOfYear: 82,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 4,
              dayOfMonth: 24,
              dayOfWeek: 'Thursday',
              dayOfYear: 83,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 5,
              dayOfMonth: 25,
              dayOfWeek: 'Friday',
              dayOfYear: 84,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 6,
              dayOfMonth: 26,
              dayOfWeek: 'Saturday',
              dayOfYear: 85,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
            {
              dayIndex: 0,
              dayOfMonth: 27,
              dayOfWeek: 'Sunday',
              dayOfYear: 86,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
          ],
        },
        {
          weekOfYear: 14,
          isCurrent: false,
          days: [
            {
              dayIndex: 1,
              dayOfMonth: 28,
              dayOfWeek: 'Monday',
              dayOfYear: 87,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 2,
              dayOfMonth: 29,
              dayOfWeek: 'Tuesday',
              dayOfYear: 88,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 3,
              dayOfMonth: 30,
              dayOfWeek: 'Wednesday',
              dayOfYear: 89,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 4,
              dayOfMonth: 31,
              dayOfWeek: 'Thursday',
              dayOfYear: 90,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 5,
              dayOfMonth: 1,
              dayOfWeek: 'Friday',
              dayOfYear: 91,
              isSameMonth: false,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 6,
              dayOfMonth: 2,
              dayOfWeek: 'Saturday',
              dayOfYear: 92,
              isSameMonth: false,
              isToday: false,
              isWeekend: true,
            },
            {
              dayIndex: 0,
              dayOfMonth: 3,
              dayOfWeek: 'Sunday',
              dayOfYear: 93,
              isSameMonth: false,
              isToday: false,
              isWeekend: true,
            },
          ],
        },
      ],
    });
  });

  test('year starting on Sunday', function () {
    const date = new Date(thatDay);
    const { result } = renderHook(() => useCalendar({ date, view: 'year' }));
    const [year] = result.current as [Year];

    expect(year.isCurrent).toBe(true);
    expect(year.isLeap).toBe(false);
    expect(year.months[2]).toEqual({
      monthIndex: 2,
      monthOfYear: 'March',
      isCurrent: true,
      weeks: [
        {
          weekOfYear: 10,
          isCurrent: false,
          days: [
            {
              dayIndex: 0,
              dayOfMonth: 27,
              dayOfWeek: 'Sunday',
              dayOfYear: 58,
              isSameMonth: false,
              isToday: false,
              isWeekend: true,
            },
            {
              dayIndex: 1,
              dayOfMonth: 28,
              dayOfWeek: 'Monday',
              dayOfYear: 59,
              isSameMonth: false,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 2,
              dayOfMonth: 1,
              dayOfWeek: 'Tuesday',
              dayOfYear: 60,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 3,
              dayOfMonth: 2,
              dayOfWeek: 'Wednesday',
              dayOfYear: 61,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 4,
              dayOfMonth: 3,
              dayOfWeek: 'Thursday',
              dayOfYear: 62,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 5,
              dayOfMonth: 4,
              dayOfWeek: 'Friday',
              dayOfYear: 63,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 6,
              dayOfMonth: 5,
              dayOfWeek: 'Saturday',
              dayOfYear: 64,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
          ],
        },
        {
          weekOfYear: 11,
          isCurrent: false,
          days: [
            {
              dayIndex: 0,
              dayOfMonth: 6,
              dayOfWeek: 'Sunday',
              dayOfYear: 65,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
            {
              dayIndex: 1,
              dayOfMonth: 7,
              dayOfWeek: 'Monday',
              dayOfYear: 66,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 2,
              dayOfMonth: 8,
              dayOfWeek: 'Tuesday',
              dayOfYear: 67,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 3,
              dayOfMonth: 9,
              dayOfWeek: 'Wednesday',
              dayOfYear: 68,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 4,
              dayOfMonth: 10,
              dayOfWeek: 'Thursday',
              dayOfYear: 69,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 5,
              dayOfMonth: 11,
              dayOfWeek: 'Friday',
              dayOfYear: 70,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 6,
              dayOfMonth: 12,
              dayOfWeek: 'Saturday',
              dayOfYear: 71,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
          ],
        },
        {
          weekOfYear: 12,
          isCurrent: false,
          days: [
            {
              dayIndex: 0,
              dayOfMonth: 13,
              dayOfWeek: 'Sunday',
              dayOfYear: 72,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
            {
              dayIndex: 1,
              dayOfMonth: 14,
              dayOfWeek: 'Monday',
              dayOfYear: 73,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 2,
              dayOfMonth: 15,
              dayOfWeek: 'Tuesday',
              dayOfYear: 74,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 3,
              dayOfMonth: 16,
              dayOfWeek: 'Wednesday',
              dayOfYear: 75,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 4,
              dayOfMonth: 17,
              dayOfWeek: 'Thursday',
              dayOfYear: 76,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 5,
              dayOfMonth: 18,
              dayOfWeek: 'Friday',
              dayOfYear: 77,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 6,
              dayOfMonth: 19,
              dayOfWeek: 'Saturday',
              dayOfYear: 78,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
          ],
        },
        {
          weekOfYear: 13,
          isCurrent: true,
          days: [
            {
              dayIndex: 0,
              dayOfMonth: 20,
              dayOfWeek: 'Sunday',
              dayOfYear: 79,
              isSameMonth: true,
              isToday: true,
              isWeekend: true,
            },
            {
              dayIndex: 1,
              dayOfMonth: 21,
              dayOfWeek: 'Monday',
              dayOfYear: 80,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 2,
              dayOfMonth: 22,
              dayOfWeek: 'Tuesday',
              dayOfYear: 81,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 3,
              dayOfMonth: 23,
              dayOfWeek: 'Wednesday',
              dayOfYear: 82,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 4,
              dayOfMonth: 24,
              dayOfWeek: 'Thursday',
              dayOfYear: 83,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 5,
              dayOfMonth: 25,
              dayOfWeek: 'Friday',
              dayOfYear: 84,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 6,
              dayOfMonth: 26,
              dayOfWeek: 'Saturday',
              dayOfYear: 85,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
          ],
        },
        {
          weekOfYear: 14,
          isCurrent: false,
          days: [
            {
              dayIndex: 0,
              dayOfMonth: 27,
              dayOfWeek: 'Sunday',
              dayOfYear: 86,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
            {
              dayIndex: 1,
              dayOfMonth: 28,
              dayOfWeek: 'Monday',
              dayOfYear: 87,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 2,
              dayOfMonth: 29,
              dayOfWeek: 'Tuesday',
              dayOfYear: 88,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 3,
              dayOfMonth: 30,
              dayOfWeek: 'Wednesday',
              dayOfYear: 89,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 4,
              dayOfMonth: 31,
              dayOfWeek: 'Thursday',
              dayOfYear: 90,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 5,
              dayOfMonth: 1,
              dayOfWeek: 'Friday',
              dayOfYear: 91,
              isSameMonth: false,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 6,
              dayOfMonth: 2,
              dayOfWeek: 'Saturday',
              dayOfYear: 92,
              isSameMonth: false,
              isToday: false,
              isWeekend: true,
            },
          ],
        },
      ],
    });
  });

  test('year starting on Sunday', function () {
    const date = new Date(thatDay);
    const { result } = renderHook(() =>
      useCalendar({ date, view: 'year', weekStartsOn: 1 }),
    );
    const [year] = result.current as [Year];

    expect(year.isCurrent).toBe(true);
    expect(year.isLeap).toBe(false);
    expect(year.months[2]).toEqual({
      monthIndex: 2,
      monthOfYear: 'March',
      isCurrent: true,
      weeks: [
        {
          weekOfYear: 10,
          isCurrent: false,
          days: [
            {
              dayIndex: 1,
              dayOfMonth: 28,
              dayOfWeek: 'Monday',
              dayOfYear: 59,
              isSameMonth: false,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 2,
              dayOfMonth: 1,
              dayOfWeek: 'Tuesday',
              dayOfYear: 60,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 3,
              dayOfMonth: 2,
              dayOfWeek: 'Wednesday',
              dayOfYear: 61,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 4,
              dayOfMonth: 3,
              dayOfWeek: 'Thursday',
              dayOfYear: 62,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 5,
              dayOfMonth: 4,
              dayOfWeek: 'Friday',
              dayOfYear: 63,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 6,
              dayOfMonth: 5,
              dayOfWeek: 'Saturday',
              dayOfYear: 64,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
            {
              dayIndex: 0,
              dayOfMonth: 6,
              dayOfWeek: 'Sunday',
              dayOfYear: 65,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
          ],
        },
        {
          weekOfYear: 11,
          isCurrent: false,
          days: [
            {
              dayIndex: 1,
              dayOfMonth: 7,
              dayOfWeek: 'Monday',
              dayOfYear: 66,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 2,
              dayOfMonth: 8,
              dayOfWeek: 'Tuesday',
              dayOfYear: 67,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 3,
              dayOfMonth: 9,
              dayOfWeek: 'Wednesday',
              dayOfYear: 68,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 4,
              dayOfMonth: 10,
              dayOfWeek: 'Thursday',
              dayOfYear: 69,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 5,
              dayOfMonth: 11,
              dayOfWeek: 'Friday',
              dayOfYear: 70,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 6,
              dayOfMonth: 12,
              dayOfWeek: 'Saturday',
              dayOfYear: 71,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
            {
              dayIndex: 0,
              dayOfMonth: 13,
              dayOfWeek: 'Sunday',
              dayOfYear: 72,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
          ],
        },
        {
          weekOfYear: 12,
          isCurrent: false,
          days: [
            {
              dayIndex: 1,
              dayOfMonth: 14,
              dayOfWeek: 'Monday',
              dayOfYear: 73,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 2,
              dayOfMonth: 15,
              dayOfWeek: 'Tuesday',
              dayOfYear: 74,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 3,
              dayOfMonth: 16,
              dayOfWeek: 'Wednesday',
              dayOfYear: 75,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 4,
              dayOfMonth: 17,
              dayOfWeek: 'Thursday',
              dayOfYear: 76,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 5,
              dayOfMonth: 18,
              dayOfWeek: 'Friday',
              dayOfYear: 77,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 6,
              dayOfMonth: 19,
              dayOfWeek: 'Saturday',
              dayOfYear: 78,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
            {
              dayIndex: 0,
              dayOfMonth: 20,
              dayOfWeek: 'Sunday',
              dayOfYear: 79,
              isSameMonth: true,
              isToday: true,
              isWeekend: true,
            },
          ],
        },
        {
          weekOfYear: 13,
          isCurrent: true,
          days: [
            {
              dayIndex: 1,
              dayOfMonth: 21,
              dayOfWeek: 'Monday',
              dayOfYear: 80,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 2,
              dayOfMonth: 22,
              dayOfWeek: 'Tuesday',
              dayOfYear: 81,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 3,
              dayOfMonth: 23,
              dayOfWeek: 'Wednesday',
              dayOfYear: 82,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 4,
              dayOfMonth: 24,
              dayOfWeek: 'Thursday',
              dayOfYear: 83,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 5,
              dayOfMonth: 25,
              dayOfWeek: 'Friday',
              dayOfYear: 84,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 6,
              dayOfMonth: 26,
              dayOfWeek: 'Saturday',
              dayOfYear: 85,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
            {
              dayIndex: 0,
              dayOfMonth: 27,
              dayOfWeek: 'Sunday',
              dayOfYear: 86,
              isSameMonth: true,
              isToday: false,
              isWeekend: true,
            },
          ],
        },
        {
          weekOfYear: 14,
          isCurrent: false,
          days: [
            {
              dayIndex: 1,
              dayOfMonth: 28,
              dayOfWeek: 'Monday',
              dayOfYear: 87,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 2,
              dayOfMonth: 29,
              dayOfWeek: 'Tuesday',
              dayOfYear: 88,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 3,
              dayOfMonth: 30,
              dayOfWeek: 'Wednesday',
              dayOfYear: 89,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 4,
              dayOfMonth: 31,
              dayOfWeek: 'Thursday',
              dayOfYear: 90,
              isSameMonth: true,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 5,
              dayOfMonth: 1,
              dayOfWeek: 'Friday',
              dayOfYear: 91,
              isSameMonth: false,
              isToday: false,
              isWeekend: false,
            },
            {
              dayIndex: 6,
              dayOfMonth: 2,
              dayOfWeek: 'Saturday',
              dayOfYear: 92,
              isSameMonth: false,
              isToday: false,
              isWeekend: true,
            },
            {
              dayIndex: 0,
              dayOfMonth: 3,
              dayOfWeek: 'Sunday',
              dayOfYear: 93,
              isSameMonth: false,
              isToday: false,
              isWeekend: true,
            },
          ],
        },
      ],
    });
  });
});
